// AUTO-GENERATED by scripts/generate-avatar-layers.js. Haath se edit mat karo.
import { ImageSourcePropType } from "react-native";

export type LayerMap = Record<string, ImageSourcePropType | undefined>;

export const FUR_BASE: LayerMap = {
};

export const FUR_PATTERN_LAYER: LayerMap = {
};

export const FUR_LENGTH_LAYER: LayerMap = {
};

export const EAR_SHAPE_LAYER: LayerMap = {
};

export const EAR_SIZE_LAYER: LayerMap = {
};

export const EAR_STYLE_LAYER: LayerMap = {
};

export const EAR_COLOR_LAYER: LayerMap = {
};

export const EYE_SHAPE_LAYER: LayerMap = {
};

export const EYE_COLOR_LAYER: LayerMap = {
};
