// AUTO-GENERATED by generate-avatar-layers.js.
// Do not edit manually.

import { ImageSourcePropType } from "react-native";

export type LayerMap = Record<
  string,
  ImageSourcePropType | undefined
>;

export const FUR_BASE: LayerMap = {
  "fur-color-1": require("../../assets/images/createMyself/fur/furcolor1.png"),
  "fur-color-2": require("../../assets/images/createMyself/fur/furcolor2.png"),
  "fur-color-3": require("../../assets/images/createMyself/fur/furcolor3.png"),
  "fur-color-4": require("../../assets/images/createMyself/fur/furcolor4.png"),
  "fur-color-5": require("../../assets/images/createMyself/fur/furcolor5.png"),
  "fur-color-6": require("../../assets/images/createMyself/fur/furcolor6.png"),
  "fur-color-7": require("../../assets/images/createMyself/fur/furcolor7.png"),
  "fur-color-8": require("../../assets/images/createMyself/fur/furcolor8.png"),
  "fur-color-9": require("../../assets/images/createMyself/fur/furcolor9.png"),
  "fur-color-10": require("../../assets/images/createMyself/fur/furcolor10.png"),
  "fur-color-11": require("../../assets/images/createMyself/fur/furcolor11.png"),
  "fur-color-12": require("../../assets/images/createMyself/fur/furcolor12.png"),
};

export const FUR_PATTERN_LAYER: LayerMap = {
  "fur-pattern-1": require("../../assets/images/createMyself/fur/furpattern1.png"),
  "fur-pattern-2": require("../../assets/images/createMyself/fur/furpattern2.png"),
  "fur-pattern-3": require("../../assets/images/createMyself/fur/furpattern3.png"),
  "fur-pattern-4": require("../../assets/images/createMyself/fur/furpattern4.png"),
  "fur-pattern-5": require("../../assets/images/createMyself/fur/furpattern5.png"),
  "fur-pattern-6": require("../../assets/images/createMyself/fur/furpattern6.png"),
};

export const FUR_LENGTH_LAYER: LayerMap = {
  "fur-length-1": require("../../assets/images/createMyself/fur/furlength1.png"),
  "fur-length-2": require("../../assets/images/createMyself/fur/furlength2.png"),
  "fur-length-3": require("../../assets/images/createMyself/fur/furlength3.png"),
};

export const EAR_SHAPE_LAYER: LayerMap = {
  "ear-shape-1": require("../../assets/images/createMyself/ears/shape1.png"),
  "ear-shape-2": require("../../assets/images/createMyself/ears/shape2.png"),
  "ear-shape-3": require("../../assets/images/createMyself/ears/shape3.png"),
  "ear-shape-4": require("../../assets/images/createMyself/ears/shape4.png"),
  "ear-shape-5": require("../../assets/images/createMyself/ears/shape5.png"),
  "ear-shape-6": require("../../assets/images/createMyself/ears/shape6.png"),
  "ear-shape-7": require("../../assets/images/createMyself/ears/shape7.png"),
  "ear-shape-8": require("../../assets/images/createMyself/ears/shape8.png"),
  "ear-shape-9": require("../../assets/images/createMyself/ears/shape9.png"),
  "ear-shape-10": require("../../assets/images/createMyself/ears/shape10.png"),
};

export const EAR_SIZE_LAYER: LayerMap = {
  "ear-size-1": require("../../assets/images/createMyself/earsize/earsize1.png"),
  "ear-size-2": require("../../assets/images/createMyself/earsize/earsize2.png"),
  "ear-size-3": require("../../assets/images/createMyself/earsize/earsize3.png"),
};

export const EAR_STYLE_LAYER: LayerMap = {
  "ear-style-1": require("../../assets/images/createMyself/earstyle/earstyle1.png"),
  "ear-style-2": require("../../assets/images/createMyself/earstyle/earstyle2.png"),
  "ear-style-3": require("../../assets/images/createMyself/earstyle/earstyle3.png"),
  "ear-style-4": require("../../assets/images/createMyself/earstyle/earstyle4.png"),
  "ear-style-5": require("../../assets/images/createMyself/earstyle/earstyle5.png"),
  "ear-style-6": require("../../assets/images/createMyself/earstyle/earstyle6.png"),
};

export const EAR_COLOR_LAYER: LayerMap = {
  "ear-color-1": require("../../assets/images/createMyself/earcolor/earcolor1.png"),
  "ear-color-2": require("../../assets/images/createMyself/earcolor/earcolor2.png"),
  "ear-color-3": require("../../assets/images/createMyself/earcolor/earcolor3.png"),
  "ear-color-4": require("../../assets/images/createMyself/earcolor/earcolor4.png"),
  "ear-color-5": require("../../assets/images/createMyself/earcolor/earcolor5.png"),
  "ear-color-6": require("../../assets/images/createMyself/earcolor/earcolor6.png"),
  "ear-color-7": require("../../assets/images/createMyself/earcolor/earcolor7.png"),
};

export const EYE_SHAPE_LAYER: LayerMap = {
  "eye-shape-1": require("../../assets/images/createMyself/eyes/shape1.png"),
  "eye-shape-2": require("../../assets/images/createMyself/eyes/shape2.png"),
  "eye-shape-3": require("../../assets/images/createMyself/eyes/shape3.png"),
  "eye-shape-4": require("../../assets/images/createMyself/eyes/shape4.png"),
  "eye-shape-5": require("../../assets/images/createMyself/eyes/shape5.png"),
  "eye-shape-6": require("../../assets/images/createMyself/eyes/shape6.png"),
  "eye-shape-7": require("../../assets/images/createMyself/eyes/shape7.png"),
  "eye-shape-8": require("../../assets/images/createMyself/eyes/shape8.png"),
  "eye-shape-9": require("../../assets/images/createMyself/eyes/shape9.png"),
  "eye-shape-10": require("../../assets/images/createMyself/eyes/shape10.png"),
};

export const EYE_COLOR_LAYER: LayerMap = {
  "eye-color-1": require("../../assets/images/createMyself/eyecolor/eyecolor1.png"),
  "eye-color-2": require("../../assets/images/createMyself/eyecolor/eyecolor2.png"),
  "eye-color-3": require("../../assets/images/createMyself/eyecolor/eyecolor3.png"),
  "eye-color-4": require("../../assets/images/createMyself/eyecolor/eyecolor4.png"),
  "eye-color-5": require("../../assets/images/createMyself/eyecolor/eyecolor5.png"),
  "eye-color-6": require("../../assets/images/createMyself/eyecolor/eyecolor6.png"),
  "eye-color-7": require("../../assets/images/createMyself/eyecolor/eyecolor7.png"),
  "eye-color-8": require("../../assets/images/createMyself/eyecolor/eyecolor8.png"),
  "eye-color-9": require("../../assets/images/createMyself/eyecolor/eyecolor9.png"),
};
